load(":pineapple.bzl", "define_pineapple")
load(":pineapple_tuivm.bzl", "define_pineapple_tuivm")
load(":pineapple_oemvm.bzl", "define_pineapple_oemvm")
load(":pineapple_vms.bzl", "define_pineapple_vms")
load(":sun.bzl", "define_sun")
load(":sun_tuivm.bzl", "define_sun_tuivm")
load(":sun_oemvm.bzl", "define_sun_oemvm")
load(":sun_vms.bzl", "define_sun_vms")
load(":msm_common.bzl", "define_signing_keys")
load("//build:msm_kernel_extensions.bzl", "define_top_level_rules")

def define_msm_platforms():
    define_top_level_rules()
    define_signing_keys()
    define_pineapple()
    define_pineapple_tuivm()
    define_pineapple_oemvm()
    define_pineapple_vms()
    define_sun()
    define_sun_tuivm()
    define_sun_oemvm()
    define_sun_vms()
